server {
  listen 80;
  server_name _;
  client_max_body_size 120m;
  root /usr/share/nginx/html;
  gzip on;
  gzip_types text/plain application/javascript text/css application/json;

  location /api/ {
    proxy_pass http://api:43124/api/;
    proxy_http_version 1.1;
    proxy_read_timeout 1800s;
    proxy_send_timeout 1800s;
    proxy_request_buffering off;
    client_max_body_size 120m;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
